In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/82105/Desktop/광주전남산불.csv')
df.head()

C:\Users\82105\AppData\Local\Temp\ipykernel_19900\2892965540.py:1: DtypeWarning: Columns (2,3,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/82105/Desktop/광주전남산불.csv')

,발생일시_년,발생일시_월,발생장소_시도,발생원인_세부원인,발생원인_기타,피해면적_합계,진화소요시간,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254
0,2022.0,12.0,전남,기타(직접입력),담뱃불실화,0.02,2:10:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022.0,12.0,전남,기타(직접입력),입산자실화,0.03,2:12:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022.0,12.0,전남,기타(직접입력),입산자실화,0.05,1:34:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022.0,12.0,전남,기타(직접입력),입산자실화,0.05,3:14:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022.0,12.0,전남,기타(직접입력),입산자실화,0.10,3:56:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.drop(df.columns[7:256], axis = 1)
df.drop(df.index[471:], axis = 0)

       발생일시_년  발생일시_월 발생장소_시도 발생원인_세부원인 발생원인_기타  피해면적_합계   진화소요시간
0      2022.0    12.0      전남  기타(직접입력)   담뱃불실화     0.02  2:10:00
1      2022.0    12.0      전남  기타(직접입력)   입산자실화     0.03  2:12:00
2      2022.0    12.0      전남  기타(직접입력)   입산자실화     0.05  1:34:00
3      2022.0    12.0      전남  기타(직접입력)   입산자실화     0.05  3:14:00
4      2022.0    12.0      전남  기타(직접입력)   입산자실화     0.10  3:56:00
...       ...     ...     ...       ...     ...      ...      ...
65529     NaN     NaN     NaN       NaN     NaN      NaN      NaN
65530     NaN     NaN     NaN       NaN     NaN      NaN      NaN
65531     NaN     NaN     NaN       NaN     NaN      NaN      NaN
65532     NaN     NaN     NaN       NaN     NaN      NaN      NaN
65533     NaN     NaN     NaN       NaN     NaN      NaN      NaN

[65534 rows x 7 columns]

In [9]:
df.drop(df.columns[7:256], axis = 1)
df.drop(df.index[471:], axis = 0)

,발생일시_년,발생일시_월,발생장소_시도,발생원인_세부원인,발생원인_기타,피해면적_합계,진화소요시간,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254
0,2022.0,12.0,전남,기타(직접입력),담뱃불실화,0.02,2:10:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022.0,12.0,전남,기타(직접입력),입산자실화,0.03,2:12:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022.0,12.0,전남,기타(직접입력),입산자실화,0.05,1:34:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022.0,12.0,전남,기타(직접입력),입산자실화,0.05,3:14:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022.0,12.0,전남,기타(직접입력),입산자실화,0.10,3:56:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,2013.0,1.0,전남,기타(직접입력),작업장실화,0.30,2:00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
recent_df = df[df['발생일시_년']>2012.0]
recent_df

,발생일시_년,발생일시_월,발생장소_시도,발생원인_세부원인,발생원인_기타,피해면적_합계,진화소요시간,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254
0,2022.0,12.0,전남,기타(직접입력),담뱃불실화,0.02,2:10:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022.0,12.0,전남,기타(직접입력),입산자실화,0.03,2:12:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022.0,12.0,전남,기타(직접입력),입산자실화,0.05,1:34:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022.0,12.0,전남,기타(직접입력),입산자실화,0.05,3:14:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022.0,12.0,전남,기타(직접입력),입산자실화,0.10,3:56:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,2013.0,2.0,전남,기타(직접입력),논두렁소각,0.50,1:10:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
463,2013.0,2.0,광주,기타(직접입력),원인미상,0.01,0:14:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
464,2013.0,2.0,광주,기타(직접입력),입산자실화,0.30,1:00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
465,2013.0,1.0,전남,기타(직접입력),논밭두렁소각,0.30,1:00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,2013.0,1.0,전남,기타(직접입력),작업장실화,0.30,2:00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
re_df = recent_df.drop(df.columns[7:256], axis = 1)
re_df

     발생일시_년  발생일시_월 발생장소_시도 발생원인_세부원인 발생원인_기타  피해면적_합계   진화소요시간
0    2022.0    12.0      전남  기타(직접입력)   담뱃불실화     0.02  2:10:00
1    2022.0    12.0      전남  기타(직접입력)   입산자실화     0.03  2:12:00
2    2022.0    12.0      전남  기타(직접입력)   입산자실화     0.05  1:34:00
3    2022.0    12.0      전남  기타(직접입력)   입산자실화     0.05  3:14:00
4    2022.0    12.0      전남  기타(직접입력)   입산자실화     0.10  3:56:00
..      ...     ...     ...       ...     ...      ...      ...
462  2013.0     2.0      전남  기타(직접입력)   논두렁소각     0.50  1:10:00
463  2013.0     2.0      광주  기타(직접입력)    원인미상     0.01  0:14:00
464  2013.0     2.0      광주  기타(직접입력)   입산자실화     0.30  1:00:00
465  2013.0     1.0      전남  기타(직접입력)  논밭두렁소각     0.30  1:00:00
466  2013.0     1.0      전남  기타(직접입력)   작업장실화     0.30  2:00:00

[467 rows x 7 columns]